### ISSUE TITLE
Exception on Math.Divide

### ISSUE THREAD

**Issue by Zulu-Inuoe** [StefH/Handlebars.Net.Helpers#42]
Hello,

I noticed that calling Math.Divide is consistently throwing an exception - System.NotSupportedException with 'Specified method is not supported.'

```csharp
            var h = Handlebars.Create();
            HandlebarsHelpers.Register(h, opt => { opt.CustomHelperPaths = new string[0]; });

            // this throws a System.NotSupportedException with Specified method is not supported.
            var x = h.Compile("{{Math.Divide 4 4}}")(null);
```

Here's the stacktrace:

```
   at HandlebarsDotNet.Helpers.HandlebarsHelpers.InvokeMethod(Nullable`1 model, Boolean methodIsOnlyUsedInContextOfABlockHelper, IHandlebars context, String helperName, MethodInfo methodInfo, Arguments arguments, Object instance)
   at HandlebarsDotNet.Helpers.HandlebarsHelpers.<>c__DisplayClass6_0.<RegisterValueHelper>b__0(Context context, Arguments arguments)
   at HandlebarsDotNet.Helpers.DelegateReturnHelperDescriptor.Invoke(EncodedTextWriter& output, HelperOptions& options, Context& context, Arguments& arguments)
   at HandlebarsDotNet.Helpers.DelegateReturnHelperDescriptor.HandlebarsDotNet.Helpers.IHelperDescriptor<HandlebarsDotNet.HelperOptions>.Invoke(EncodedTextWriter& output, HelperOptions& options, Context& context, Arguments& arguments)
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass15_0.<Compile>b__0(TextWriter writer, Object context, Object data)
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass16_0.<Compile>b__0(Object context, Object data)
 ```

**Comment by StefH** [comment]
Hello @Zulu-Inuoe,

This is a strange issue. It should work fine.
See my updated unit tests:
https://github.com/Handlebars-Net/Handlebars.Net.Helpers/blob/math-divide/test/Handlebars.Net.Helpers.Tests/Templates/MathHelpersTemplateTests.cs#L41
